name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - user: pnpm/actions-setup@v2
        with:
          version: 7
      - user: pnpm/action-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
