name: Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version you want to use

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies with PNPM
        run: pnpm install

      - name: Build the React app
        run: pnpm run build
